"""rename department

Revision ID: 525dc9deb94c
Revises: f203e30eedb7
Create Date: 2024-02-01 14:09:22.135244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525dc9deb94c'
down_revision = 'f203e30eedb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ##rename_table takes 2 parameters, old name and new name
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
