"""rename address

Revision ID: d47c94dc76bb
Revises: 525dc9deb94c
Create Date: 2024-02-01 14:12:28.066245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47c94dc76bb'
down_revision = '525dc9deb94c'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('departments', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
#         batch_op.drop_column('address')

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('departments', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
#         batch_op.drop_column('location')

#     # ### end Alembic commands ###
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###